#!/usr/bin/env node

if (!process.env.AWS_ACCESS_KEY || !process.env.AWS_SECRET_KEY) {
  console.log('Not deploying assets. No AWS credentials found.');
  process.exit();
}

var s3 = require('s3');

var client = s3.createClient({
  maxAsyncS3: Infinity
, s3RetryCount: 3
, s3RetryDelay: 1000
, s3Options: {
    accessKeyId: process.env.AWS_ACCESS_KEY
  , secretAccessKey: process.env.AWS_SECRET_KEY
  }
});

var params = {
  localDir: 'public/assets'
, s3Params: {
    Bucket: 'expressjs-base'
  , Prefix: 'assets/'
  }
};

var uploader = client.uploadDir(params);

uploader.on('error', function(err) {
  console.error('Error uploading  assets:', err.stack);
});

uploader.on('end', function() {
  console.log('Done uploading assets');
});
